### ISSUE TITLE
Create User api ignores first_name, last_name

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/crm-users-module#1]
Despite the example in the documentation, users' first_name and last_name are not being saved. It would also be good to be able to save other fields like frm-userForm-ext_id. I'd suggest that the user creation process be made more flexible for more fields in the future.

https://github.com/remp2020/crm-users-module/blob/ed25f752c034908bcb20fa0d37b94f163f52a29f/src/api/UsersCreateHandler.php#L50

https://github.com/remp2020/crm-users-module/blob/ed25f752c034908bcb20fa0d37b94f163f52a29f/src/model/Auth/UserManager.php#L84

**Comment by rootpd** [comment]
True. We'll look at the list of available fields and add all reasonable fields to the API call as optional parameters.

**Comment by rootpd** [comment]
Until we release it, let me just point you to https://github.com/remp2020/crm-skeleton#registerapicalls, which describes a way how you can extend CRM with your own API calls.

With that, you could make your own register API that could accept all the fields. And if you used `UsersCreateHandler` as an example, it wouldn't take that long.

(not trying to force you into that, it should be that easy for us too :) )

**Comment by j-norwood-young** [comment]
I think the right thing to do in this case is to fix this module rather than writing another API to do the same thing. I'll fix it myself and send a pull request when done.

**Comment by markoph** [comment]
I am already working on it. Will be ready today.

**Comment by markoph** [comment]
We looked at `users` table columns and added new optional fields to this API handler:

- `first_name`
- `last_name`
- `ext_id`
- `note`

----

Note: All modules were released (0.3.1). You need to update your configuration files _(`.env` and `app/config.neon`)_. See example of change here https://github.com/remp2020/crm-skeleton/commit/8480da58c5754c215ed0ad47a75e6e06f135a8c6 _(we are now using language variant code; so if you used `en`, you have to change it to `en_US`)_.
