### ISSUE TITLE
Translation missing on User Meta tab

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/crm-users-module#2]
Under users/users-admin/show/<user_id>, User Meta tab is not translated.
<img width="721" alt="Screenshot 2019-06-25 at 09 35 54" src="https://user-images.githubusercontent.com/387601/60078725-ce7a7d80-972c-11e9-9097-a14df91e751a.png">

**Comment by rootpd** [comment]
The translations have been added and will be part of the next (`0.3.3` / `0.4.0`) release.
